
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsfeed
    username: root
    password: root
  jpa:
      database: mysql
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update